DOTFILES=$HOME/Code/dotfiles
ZSHFILES=$DOTFILES/zsh

source $ZSHFILES/directories.zsh
source $ZSHFILES/history.zsh
source $ZSHFILES/git.zsh
source $ZSHFILES/history.zsh
source $ZSHFILES/paths.zsh

autoload -U colors && colors
autoload -U promptinit && promptinit
autoload -U add-zsh-hook

setopt prompt_subst
PROMPT="%{$fg[magenta]%}%n%{$reset_color%}@%{$fg[yellow]%}%m%{$reset_color%}:%~ "

exec bash
