DOTFILES=$HOME/Code/dotfiles
ZSHFILES=$DOTFILES/zsh

source $ZSHFILES/completion.zsh
source $ZSHFILES/directories.zsh
source $ZSHFILES/history.zsh
source $ZSHFILES/git.zsh
source $ZSHFILES/keybinds.zsh
source $ZSHFILES/paths.zsh
source $ZSHFILES/misc.zsh

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
